"""Seed script for static game config: unit and upgrade definitions.

Run once after ``alembic upgrade head``:
    python -m app.db.seed
"""

import asyncio
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models.unit import UnitDefinition
from app.db.models.upgrade import UpgradeDefinition
from app.db.session import AsyncSessionLocal

# Seed data stored as plain dicts — ORM instances are created fresh on each
# seed() call to avoid SQLAlchemy identity-map issues across test sessions.
_UNIT_DATA: list[dict] = [  # type: ignore[type-arg]
    # --- Tier 1: produce energy_drink ---
    dict(
        id="barrel",
        name="Beczka Energetyka",
        tier=1,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("15"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="energy_drink",
        production_rate_per_sec=Decimal("0.3"),
        unlocked_by=None,
    ),
    dict(
        id="mini_reactor",
        name="Mini Reaktor Uranowy",
        tier=1,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("100"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="energy_drink",
        production_rate_per_sec=Decimal("1.5"),
        unlocked_by=None,
    ),
    dict(
        id="isotope_lab",
        name="Laboratorium Izotopów",
        tier=1,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("1100"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="energy_drink",
        production_rate_per_sec=Decimal("12.0"),
        unlocked_by=None,
    ),
    dict(
        id="processing_plant",
        name="Zakład Przetwórczy",
        tier=1,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("12000"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="energy_drink",
        production_rate_per_sec=Decimal("30.0"),
        unlocked_by=None,
    ),
    dict(
        id="uranium_mine",
        name="Kopalnia Uranu",
        tier=1,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("130000"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="energy_drink",
        production_rate_per_sec=Decimal("120.0"),
        unlocked_by=None,
    ),
    # --- Tier 1 bridge: high-end ED producer ---
    dict(
        id="uranium_refinery",
        name="Rafineria Uranu",
        tier=1,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("600000"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="energy_drink",
        production_rate_per_sec=Decimal("80.0"),
        unlocked_by=None,
    ),
    # --- Tier 2: produce u238, cost energy_drink ---
    dict(
        id="centrifuge_t2",
        name="Wirówka Izotopowa",
        tier=2,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("3000000"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="u238",
        production_rate_per_sec=Decimal("0.003"),
        unlocked_by=None,
    ),
    dict(
        id="enrichment_facility",
        name="Zakład Wzbogacania",
        tier=2,
        base_cost_currency="energy_drink",
        base_cost_amount=Decimal("30000000"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="u238",
        production_rate_per_sec=Decimal("0.015"),
        unlocked_by=None,
    ),
    # --- Tier 3: produce u235, cost u238 ---
    dict(
        id="isotope_separator",
        name="Separator Izotopów",
        tier=3,
        base_cost_currency="u238",
        base_cost_amount=Decimal("5"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="u235",
        production_rate_per_sec=Decimal("0.001"),
        unlocked_by=None,
    ),
    dict(
        id="quantum_centrifuge",
        name="Kwantowa Wirówka",
        tier=3,
        base_cost_currency="u238",
        base_cost_amount=Decimal("50"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="u235",
        production_rate_per_sec=Decimal("0.008"),
        unlocked_by=None,
    ),
    # --- Tier 4: produce u233, cost u235 ---
    dict(
        id="thorium_converter",
        name="Konwerter Torowy",
        tier=4,
        base_cost_currency="u235",
        base_cost_amount=Decimal("2"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="u233",
        production_rate_per_sec=Decimal("0.001"),
        unlocked_by=None,
    ),
    dict(
        id="breeder_reactor",
        name="Reaktor Hodowlany",
        tier=4,
        base_cost_currency="u235",
        base_cost_amount=Decimal("25"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="u233",
        production_rate_per_sec=Decimal("0.007"),
        unlocked_by=None,
    ),
    # --- Tier 5: produce meta_isotopes, cost u233 ---
    dict(
        id="particle_accelerator",
        name="Akcelerator Cząstek",
        tier=5,
        base_cost_currency="u233",
        base_cost_amount=Decimal("1"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="meta_isotopes",
        production_rate_per_sec=Decimal("0.001"),
        unlocked_by=None,
    ),
    dict(
        id="dimension_reactor",
        name="Reaktor Wymiarowy",
        tier=5,
        base_cost_currency="u233",
        base_cost_amount=Decimal("15"),
        cost_growth_type="linear_early_exp_late",
        cost_growth_factor=Decimal("1.15"),
        production_resource="meta_isotopes",
        production_rate_per_sec=Decimal("0.006"),
        unlocked_by=None,
    ),
]

_UPGRADE_DATA: list[dict] = [  # type: ignore[type-arg]
    dict(
        id="barrel_opt_mk1",
        name="Optymalizacja Beczki",
        description="Beczki produkują 10% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("200"),
        effect_type="prod_mult",
        effect_value=Decimal("1.10"),
        target_unit_id="barrel",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="reactor_tuning_mk1",
        name="Strojenie Reaktora",
        description="Mini Reaktory Uranowe produkują 20% więcej.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("1000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="mini_reactor",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="offline_module_mk1",
        name="Moduł Offline Mk1",
        description="Zwiększa efektywność produkcji offline o 5%.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("300"),
        effect_type="offline_eff_up",
        effect_value=Decimal("0.05"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    dict(
        id="offline_module_mk2",
        name="Moduł Offline Mk2",
        description="Zwiększa efektywność produkcji offline o kolejne 10%.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("5000"),
        effect_type="offline_eff_up",
        effect_value=Decimal("0.10"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    dict(
        id="offline_cap_mk1",
        name="Rozszerzenie Bufora Offline Mk1",
        description="Zwiększa maksymalny czas offline o 2 godziny.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("2000"),
        effect_type="offline_cap_up",
        effect_value=Decimal("7200"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    dict(
        id="offline_cap_mk2",
        name="Rozszerzenie Bufora Offline Mk2",
        description="Zwiększa maksymalny czas offline o kolejne 4 godziny.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("20000"),
        effect_type="offline_cap_up",
        effect_value=Decimal("14400"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    # --- B1-B6: Mk2 upgrades for T1 units ---
    dict(
        id="barrel_opt_mk2",
        name="Optymalizacja Beczki Mk2",
        description="Beczki produkują 20% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("2000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="barrel",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="reactor_tuning_mk2",
        name="Strojenie Reaktora Mk2",
        description="Mini Reaktory produkują 25% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("12000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.25"),
        target_unit_id="mini_reactor",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="lab_efficiency_mk1",
        name="Wydajność Laboratorium Mk1",
        description="Laboratoria Izotopów produkują 20% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("25000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="isotope_lab",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="plant_overdrive_mk1",
        name="Przeciążenie Zakładu Mk1",
        description="Zakłady Przetwórcze produkują 25% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("250000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.25"),
        target_unit_id="processing_plant",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="mine_excavation_mk1",
        name="Eksploatacja Kopalni Mk1",
        description="Kopalnie Uranu produkują 30% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("2500000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.30"),
        target_unit_id="uranium_mine",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="refinery_boost_mk1",
        name="Doładowanie Rafinerii Mk1",
        description="Rafinerie Uranu produkują 20% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("1200000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="uranium_refinery",
        is_repeatable=False,
        survives_prestige=False,
    ),
    # --- E1-E7: T2 upgrades + T1 Mk3 ---
    dict(
        id="centrifuge_boost_mk1",
        name="Boost Wirówki Mk1",
        description="Wirówki Izotopowe produkują 20% więcej U-238.",
        tier=2,
        cost_currency="energy_drink",
        cost_amount=Decimal("15000000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="centrifuge_t2",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="enrichment_tuning_mk1",
        name="Strojenie Zakładu Wzbogacania Mk1",
        description="Zakłady Wzbogacania produkują 20% więcej U-238.",
        tier=2,
        cost_currency="energy_drink",
        cost_amount=Decimal("150000000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="enrichment_facility",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="barrel_opt_mk3",
        name="Optymalizacja Beczki Mk3",
        description="Beczki produkują jeszcze 25% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("20000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.25"),
        target_unit_id="barrel",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="reactor_tuning_mk3",
        name="Strojenie Reaktora Mk3",
        description="Mini Reaktory produkują jeszcze 30% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("120000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.30"),
        target_unit_id="mini_reactor",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="lab_efficiency_mk2",
        name="Wydajność Laboratorium Mk2",
        description="Laboratoria Izotopów produkują 25% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("250000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.25"),
        target_unit_id="isotope_lab",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="plant_overdrive_mk2",
        name="Przeciążenie Zakładu Mk2",
        description="Zakłady Przetwórcze produkują 30% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("2500000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.30"),
        target_unit_id="processing_plant",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="mine_excavation_mk2",
        name="Eksploatacja Kopalni Mk2",
        description="Kopalnie Uranu produkują 35% więcej energetyka.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("25000000"),
        effect_type="prod_mult",
        effect_value=Decimal("1.35"),
        target_unit_id="uranium_mine",
        is_repeatable=False,
        survives_prestige=False,
    ),
    # --- F1-F2: Offline Mk3 upgrades ---
    dict(
        id="offline_module_mk3",
        name="Moduł Offline Mk3",
        description="Zwiększa efektywność produkcji offline o kolejne 15%.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("50000"),
        effect_type="offline_eff_up",
        effect_value=Decimal("0.15"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    dict(
        id="offline_cap_mk3",
        name="Rozszerzenie Bufora Offline Mk3",
        description="Zwiększa maksymalny czas offline o kolejne 8 godzin.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("200000"),
        effect_type="offline_cap_up",
        effect_value=Decimal("28800"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    # --- G1-G3: Global upgrades ---
    dict(
        id="global_prod_mk1",
        name="Globalny Akcelerator Mk1",
        description="Wszystkie jednostki produkują 10% więcej — efekt globalny.",
        tier=2,
        cost_currency="energy_drink",
        cost_amount=Decimal("500000"),
        effect_type="global_prod_mult",
        effect_value=Decimal("1.10"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    dict(
        id="starting_bonus_mk1",
        name="Bonus Startowy Mk1",
        description="Natychmiast dodaje 50 000 energetyka do portfela.",
        tier=1,
        cost_currency="energy_drink",
        cost_amount=Decimal("100000"),
        effect_type="starting_energy_up",
        effect_value=Decimal("50000"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    dict(
        id="global_prod_mk2",
        name="Globalny Akcelerator Mk2",
        description="Wszystkie jednostki produkują 15% więcej — efekt globalny.",
        tier=2,
        cost_currency="energy_drink",
        cost_amount=Decimal("5000000"),
        effect_type="global_prod_mult",
        effect_value=Decimal("1.15"),
        target_unit_id=None,
        is_repeatable=False,
        survives_prestige=True,
    ),
    # --- H1-H6: T3-T5 unit upgrades ---
    dict(
        id="separator_boost_mk1",
        name="Boost Separatora Mk1",
        description="Separatory Izotopów produkują 20% więcej U-235.",
        tier=3,
        cost_currency="u238",
        cost_amount=Decimal("20"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="isotope_separator",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="quantum_boost_mk1",
        name="Boost Kwantowej Wirówki Mk1",
        description="Kwantowe Wirówki produkują 25% więcej U-235.",
        tier=3,
        cost_currency="u238",
        cost_amount=Decimal("150"),
        effect_type="prod_mult",
        effect_value=Decimal("1.25"),
        target_unit_id="quantum_centrifuge",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="thorium_opt_mk1",
        name="Optymalizacja Konwertera Mk1",
        description="Konwertery Torowe produkują 20% więcej U-233.",
        tier=4,
        cost_currency="u235",
        cost_amount=Decimal("8"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="thorium_converter",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="breeder_boost_mk1",
        name="Boost Reaktora Hodowlanego Mk1",
        description="Reaktory Hodowlane produkują 25% więcej U-233.",
        tier=4,
        cost_currency="u235",
        cost_amount=Decimal("80"),
        effect_type="prod_mult",
        effect_value=Decimal("1.25"),
        target_unit_id="breeder_reactor",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="accelerator_mk1",
        name="Ulepszenie Akceleratora Mk1",
        description="Akceleratory Cząstek produkują 20% więcej meta-izotopów.",
        tier=5,
        cost_currency="u233",
        cost_amount=Decimal("3"),
        effect_type="prod_mult",
        effect_value=Decimal("1.20"),
        target_unit_id="particle_accelerator",
        is_repeatable=False,
        survives_prestige=False,
    ),
    dict(
        id="dimension_boost_mk1",
        name="Boost Reaktora Wymiarowego Mk1",
        description="Reaktory Wymiarowe produkują 25% więcej meta-izotopów.",
        tier=5,
        cost_currency="u233",
        cost_amount=Decimal("40"),
        effect_type="prod_mult",
        effect_value=Decimal("1.25"),
        target_unit_id="dimension_reactor",
        is_repeatable=False,
        survives_prestige=False,
    ),
]


async def seed(session: AsyncSession) -> None:
    """Upsert all static game config rows (insert or update in-place).

    Idempotent — safe to run multiple times; existing rows are updated to
    reflect current balance values (production rates, costs, etc.).

    Args:
        session: Active async database session (caller commits).
    """
    existing_units = {
        u.id: u for u in (await session.execute(select(UnitDefinition))).scalars().all()
    }
    for data in _UNIT_DATA:
        if data["id"] in existing_units:
            obj = existing_units[data["id"]]
            for k, v in data.items():
                setattr(obj, k, v)
        else:
            session.add(UnitDefinition(**data))

    existing_upgrades = {
        u.id: u for u in (await session.execute(select(UpgradeDefinition))).scalars().all()
    }
    for data in _UPGRADE_DATA:
        if data["id"] in existing_upgrades:
            obj = existing_upgrades[data["id"]]
            for k, v in data.items():
                setattr(obj, k, v)
        else:
            session.add(UpgradeDefinition(**data))

    await session.flush()


async def _main() -> None:
    async with AsyncSessionLocal() as session:
        async with session.begin():
            await seed(session)
    print("Seed complete.")


if __name__ == "__main__":
    asyncio.run(_main())
